[package]
name = "firewall"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-uds = "0.2"
reqwest = { version = "0.12.15", features = ["blocking"] }
serde_json = "1.0.140"
dashmap = "6.1.0"
